### ISSUE TITLE
[ISSUE] Panic when using `idempotency_token`

### ISSUE THREAD

**Issue by Happycoil** [databrickslabs/terraform-provider-databricks#103]
### Terraform Version
`Terraform v0.12.26`

### Affected Resource(s)
- databricks_cluster

### Terraform Configuration Files
```hcl
resource "databricks_cluster" "main" {
  cluster_name            = "default"
  num_workers             = 1
  spark_version           = "6.4.x-scala2.11"
  node_type_id            = var.default_cluster_node_size
  autotermination_minutes = 0
  idempotency_token       = 6414
}
```

### Panic Output
```
panic: interface conversion: interface {} is int, not string
2020-06-15T11:14:40.339Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: 
2020-06-15T11:14:40.339Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: goroutine 52 [running]:
2020-06-15T11:14:40.339Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: github.com/databrickslabs/databricks-terraform/databricks.parseSchemaToCluster(0xc000128540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2020-06-15T11:14:40.339Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: 	/home/runner/work/databricks-terraform/databricks-terraform/databricks/resource_databricks_cluster.go:1436 +0x2153
2020-06-15T11:14:40.339Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: github.com/databrickslabs/databricks-terraform/databricks.resourceClusterCreate(0xc000128540, 0x10388e0, 0xc00000ed58, 0x2, 0x1a1f6c0)
2020-06-15T11:14:40.339Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: 	/home/runner/work/databricks-terraform/databricks-terraform/databricks/resource_databricks_cluster.go:508 +0x63
2020-06-15T11:14:40.339Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00043c480, 0xc000112690, 0xc0004703e0, 0x10388e0, 0xc00000ed58, 0xc00008c801, 0xc000266ed0, 0xc00008c8c8)
2020-06-15T11:14:40.339Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.13.0/helper/schema/resource.go:310 +0x365
2020-06-15T11:14:40.339Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0000fea80, 0xc00027f9c8, 0xc000112690, 0xc0004703e0, 0xc0002394c8, 0xc0004689d0, 0xef6320)
2020-06-15T11:14:40.339Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.13.0/helper/schema/provider.go:294 +0x99
2020-06-15T11:14:40.339Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000ec08, 0x12c8f60, 0xc00012d560, 0xc000128000, 0xc00000ec08, 0xc00012d560, 0xc000184b30)
2020-06-15T11:14:40.339Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.13.0/internal/helper/plugin/grpc_provider.go:885 +0x8b4
2020-06-15T11:14:40.339Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x10307e0, 0xc00000ec08, 0x12c8f60, 0xc00012d560, 0xc00001d080, 0x0, 0x12c8f60, 0xc00012d560, 0xc0000a8d80, 0x415)
2020-06-15T11:14:40.339Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.13.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x217
2020-06-15T11:14:40.339Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000410900, 0x12d4b60, 0xc000411380, 0xc000388300, 0xc000081a10, 0x19f2c40, 0x0, 0x0, 0x0)
2020-06-15T11:14:40.339Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1024 +0x4f4
2020-06-15T11:14:40.339Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: google.golang.org/grpc.(*Server).handleStream(0xc000410900, 0x12d4b60, 0xc000411380, 0xc000388300, 0x0)
2020-06-15T11:14:40.339Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1313 +0xd97
2020-06-15T11:14:40.339Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0002e4150, 0xc000410900, 0x12d4b60, 0xc000411380, 0xc000388300)
2020-06-15T11:14:40.340Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:722 +0xbb
2020-06-15T11:14:40.340Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-06-15T11:14:40.340Z [DEBUG] plugin.terraform-provider-databricks_v0.2.0: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:720 +0xa1
2020-06-15T11:14:40.340Z [DEBUG] plugin: plugin process exited: path=/terraform/.terraform/plugins/linux_amd64/terraform-provider-databricks_v0.2.0 pid=1592 error="exit status 2"
```

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
I don't really know go yet, but is the parameter defined as an [integer](https://github.com/databrickslabs/databricks-terraform/blob/master/databricks/resource_databricks_cluster.go#L306-L310) and later panics at [this](https://github.com/databrickslabs/databricks-terraform/blob/master/databricks/resource_databricks_cluster.go#L1435) line?

**Comment by stikkireddy** [comment]
@Happycoil thanks for pointing this out, will be working on an integration test for this, it is an easy fix but want to make sure that this resource is covered.

**Comment by nfx** [comment]
will be covered in #17
