### ISSUE TITLE
[ISSUE] databricks_cluster failed with: segmentation violation code=0x1 addr=0x28 pc=0x1a37621

### ISSUE THREAD

**Issue by panderso01** [databrickslabs/terraform-provider-databricks#187]
terraform apply crashed while attempting to create Databricks cluster within Azure Databricks workspace. Cluster was created.
[crash.log](https://github.com/databrickslabs/terraform-provider-databricks/files/4950221/crash.log)

**Comment by fredrikcelin** [comment]
I think it is this:
https://github.com/databrickslabs/terraform-provider-databricks/commit/249cc8ffb99583684e1f00ff90239cdaef52eb45#r40770174

I get same error.
In crash.log:1347
2020-07-20T14:27:36.668-0700 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/databricks/resource_databricks_cluster.go:710 +0x931

**Comment by stikkireddy** [comment]
```go
isInstanceProfileArnFound := !reflect.ValueOf(clusterInfo.AwsAttributes.InstanceProfileArn).IsZero()
```
 that should be replaced with 
```go
isInstanceProfileArnFound := clusterInfo.AwsAttributes != nil && !reflect.ValueOf(clusterInfo.AwsAttributes.InstanceProfileArn).IsZero()
```

**Comment by sdebruyn** [comment]
I am running from a build from the latest master branch and this is still happening, so the code above was not the culprit as it has been removed since

**Comment by sdebruyn** [comment]
Current stacktrace:

```
databricks_cluster.cluster: Creating...
databricks_cluster.cluster: Still creating... [10s elapsed]
databricks_cluster.cluster: Still creating... [20s elapsed]
databricks_cluster.cluster: Still creating... [30s elapsed]
databricks_cluster.cluster: Still creating... [40s elapsed]
databricks_cluster.cluster: Still creating... [50s elapsed]
databricks_cluster.cluster: Still creating... [1m0s elapsed]

Error: rpc error: code = Canceled desc = context canceled


panic: runtime error: invalid memory address or nil pointer dereference
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xe38151]
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: goroutine 28 [running]:
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: github.com/databrickslabs/databricks-terraform/databricks.resourceClusterRead(0xc0002e75e0, 0x10d3940, 0xc00000e908, 0x1e, 0x78)
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/databricks/resource_databricks_cluster.go:710 +0x931
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: github.com/databrickslabs/databricks-terraform/databricks.resourceClusterCreate(0xc0002e75e0, 0x10d3940, 0xc00000e908, 0x2, 0x1b72120)
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/databricks/resource_databricks_cluster.go:553 +0x237
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00047d200, 0xc0002b0eb0, 0xc0004b28c0, 0x10d3940, 0xc00000e908, 0xc000455501, 0xc0004c22a0, 0xc0004555a0)
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/resource.go:310 +0x365
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000104e00, 0xc0005419c8, 0xc0002b0eb0, 0xc0004b28c0, 0xc000470868, 0xc00046d1f8, 0xf81120)
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/provider.go:294 +0x99
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000ec58, 0x13c8d20, 0xc000416f00, 0xc0002e6f50, 0xc00000ec58, 0xc000416f00, 0xc000089b30)
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/helper/plugin/grpc_provider.go:885 +0x8b4
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x10c5cc0, 0xc00000ec58, 0x13c8d20, 0xc000416f00, 0xc000231b00, 0x0, 0x13c8d20, 0xc000416f00, 0xc000264f00, 0x4cf)
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x217
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000440900, 0x13d5300, 0xc000441680, 0xc0000d7000, 0xc0001069f0, 0x1b453a0, 0x0, 0x0, 0x0)
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1024 +0x4f4
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: google.golang.org/grpc.(*Server).handleStream(0xc000440900, 0x13d5300, 0xc000441680, 0xc0000d7000, 0x0)
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1313 +0xd97
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00003c410, 0xc000440900, 0x13d5300, 0xc000441680, 0xc0000d7000)
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:722 +0xbb
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-08-05T21:01:32.593Z [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:720 +0xa1
2020-08-05T21:01:32.595Z [DEBUG] plugin: plugin process exited: path=/home/vsts/.terraform.d/plugins/terraform-provider-databricks_v0.2.3 pid=7152 error="exit status 2"
2020/08/05 21:01:32 [DEBUG] databricks_cluster.cluster: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Canceled desc = context canceled
2020/08/05 21:01:32 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/08/05 21:01:32 [TRACE] EvalMaybeTainted: databricks_cluster.cluster encountered an error during creation, so it is now marked as tainted
2020/08/05 21:01:32 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/08/05 21:01:32 [TRACE] EvalWriteState: removing state object for databricks_cluster.cluster
2020/08/05 21:01:32 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
```

**Comment by sdebruyn** [comment]
It seems like this is fixed with the code that is currently on master. I could reproduce it with 0.2.3 but I can't anymore with the latest master.

**Comment by stikkireddy** [comment]
@panderso01 this should be resolved in master and on the next release
