### ISSUE TITLE
[ISSUE] Error: rpc error: code = Unavailable desc = transport is closing (when creating cluster)

### ISSUE THREAD

**Issue by dgonzalezp** [databrickslabs/terraform-provider-databricks#223]
### Terraform Version
Terraform v0.12.29

### Affected Resource(s)
- databricks_cluster

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "azurerm" {
    version = "~>2.21.0"
    features {}
}

terraform {
  backend "azurerm" {
    storage_account_name  = "somestorageacc"
    container_name        = "tfstate"
    key                   = "terrafrom.tfstate"
  }
}

resource "azurerm_resource_group" "rg_databricks" {
  name     = "rg-dbw-appname"
  location = var.location
}

resource "azurerm_databricks_workspace" "dbw" {
  name                        = "dbw-appname"
  resource_group_name         = azurerm_resource_group.rg_databricks.name
  location                    = azurerm_resource_group.rg_databricks.location
  sku                         = "standard"

  managed_resource_group_name = "rg-dbw-appname-resources"

  custom_parameters {
    virtual_network_id  = azurerm_virtual_network.vnet.id
    private_subnet_name = azurerm_subnet.dbw_private_subnet.name
    public_subnet_name  = azurerm_subnet.dbw_public_subnet.name
  }
  
  tags = {
    Environment = "Dev"
  }
}

provider "databricks" {
  version = "~>0.2.3"
  azure_auth = {
    workspace_name         = azurerm_databricks_workspace.dbw.name
    resource_group         = azurerm_databricks_workspace.dbw.resource_group_name
    managed_resource_group = azurerm_databricks_workspace.dbw.managed_resource_group_name
    azure_region           = azurerm_databricks_workspace.dbw.location
    client_id              = "***"
    client_secret          = "***"
    tenant_id              = "***"
    subscription_id        = "***"
  }
}

variable "db_user_name_list" {
  description = "User list"
  type        = list(string)
  default     = ["user1@email.com", "user2@email.com"]
}

variable "db_display_name_list" {
  description = "User list"
  type        = list(string)
  default     = ["User 1", "User 2"]
}

resource "databricks_scim_user" "db_user" {
  count         = 2
  user_name     = var.db_user_name_list[count.index]
  display_name  = var.db_display_name_list[count.index]
  default_roles = []
  set_admin     = true
  entitlements  = [
    "allow-cluster-create",
    "allow-instance-pool-create"
  ]
}

resource "databricks_cluster" "db_cluster" {
  cluster_name            = "db-cluster-appname"
  spark_version           = "6.6.x-scala2.11"
  node_type_id            = "Standard_DS3_v2"
  autotermination_minutes = 20
  single_user_name        = "user@email.com"

  autoscale {
    min_workers = 1
    max_workers = 3
  }
}
```

### Debug Output
databricks_cluster.db_cluster: Still creating... [4m10s elapsed]

Error: rpc error: code = Unavailable desc = transport is closing

Releasing state lock. This may take a few moments...

Please list the steps required to reproduce the issue, for example:
1. `terraform apply --auto-approve`

**Comment by dgonzalezp** [comment]
Just a note, private and public subnets are created as well, the workspace is correctly created in those subnets, the issue occurs creating the cluster

**Comment by nfx** [comment]
@dgonzalezp which version of the provider? current master has retries on connection refusals & timeout for 30 minutes.

**Comment by dgonzalezp** [comment]
azurerm 2.21.0
databricks 0.2.3

**Comment by grgouveia** [comment]
Had the same issue and the downgrade to previous version 0.2.2 solved my problem.

**Comment by phlope** [comment]
Had a similar issue when adding a library_jar referencing DBFS, plans fine but hitting the same error you are at apply.
Downgrading to 0.2.2 hasn't solved it unfortunately

**Comment by dgonzalezp** [comment]
Yes It continues to happen in version 0.2.2 to me as well

% terraform providers
.
├── provider.azurerm ~>2.21.0
├── provider.databricks ~> 0.2.2

```bash
databricks_cluster.db_cluster: Still creating... [4m0s elapsed]

Error: rpc error: code = Unavailable desc = transport is closing

Releasing state lock. This may take a few moments...
````

**Comment by nfx** [comment]
@dgonzalezp current master has retries on transport errors. can you check if it's solving your issue?

**Comment by nfx** [comment]
@dgonzalezp , why do you need `databricks_scim_user`, btw? isn't AAD SCIM provisioning working for you?..

**Comment by dgonzalezp** [comment]
Ahh yes I can get rid of those users, I'm following the tutorials for creating the resources and wanted to see if the user creation was successful. But I'm still getting the error. When you talk about current master is it version 0.2.3 or does the transport errors retries are newer? Thanks for you answer.

**Comment by markhoiland** [comment]
I'm also having this same issue with the versions below, as well as attempts with 0.2.2.

Terraform v0.13.0
+ provider registry.terraform.io/databrickslabs/databricks v0.2.3
+ provider registry.terraform.io/hashicorp/azurerm v2.22.0

**Comment by stikkireddy** [comment]
@dgonzalezp can you provide the debug/panic output? you can get that by setting TF_LOG=debug and also provide the crash.log. Error: rpc error: code = Unavailable desc = transport is closing is a terraform issue not sure what exactly is causing it.

**Comment by dgonzalezp** [comment]
```bash
2020-08-18T12:02:22.009-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 2020/08/18 12:02:22 {"Method":"GET","URI":"https://adb-7511418462624412.12.azuredatabricks.net/api/2.0/clusters/get?cluster_id=0818-165759-dairy751"}
2020-08-18T12:02:22.563-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 2020/08/18 12:02:22 ALREADY AUTHORIZED
2020-08-18T12:02:22.563-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 2020/08/18 12:02:22 {"Method":"GET","URI":"https://adb-7511418462624412.12.azuredatabricks.net/api/2.0/libraries/cluster-status?cluster_id=0818-165759-dairy751"}
2020-08-18T12:02:23.321-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1a37621]
2020-08-18T12:02:23.321-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 
2020-08-18T12:02:23.321-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: goroutine 65 [running]:
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: github.com/databrickslabs/databricks-terraform/databricks.resourceClusterRead(0xc0003dee00, 0x1cd26a0, 0xc0000acd70, 0x1e, 0x78)
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/databricks/resource_databricks_cluster.go:710 +0x931
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: github.com/databrickslabs/databricks-terraform/databricks.resourceClusterCreate(0xc0003dee00, 0x1cd26a0, 0xc0000acd70, 0x2, 0x2774c20)
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/databricks/resource_databricks_cluster.go:553 +0x237
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0005223f0, 0xc0004733b0, 0xc0004f6c00, 0x1cd26a0, 0xc0000acd70, 0xc0003b1501, 0xc0003ead80, 0xc0003b1588)
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/resource.go:310 +0x365
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00048a000, 0xc0002659c8, 0xc0004733b0, 0xc0004f6c00, 0xc000314ce8, 0xc00048ee88, 0x1b7fd20)
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/provider.go:294 +0x99
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000e008, 0x1fc7fa0, 0xc0002afd40, 0xc0003de8c0, 0xc00000e008, 0xc0002afd40, 0xc0005d3b30)
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/helper/plugin/grpc_provider.go:885 +0x8b4
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1cc4d60, 0xc00000e008, 0x1fc7fa0, 0xc0002afd40, 0xc0000af0e0, 0x0, 0x1fc7fa0, 0xc0002afd40, 0xc0002ba000, 0x473)
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x217
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00007f680, 0x1fd4800, 0xc00053e480, 0xc00021e100, 0xc00008f3e0, 0x2748500, 0x0, 0x0, 0x0)
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1024 +0x4f4
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: google.golang.org/grpc.(*Server).handleStream(0xc00007f680, 0x1fd4800, 0xc00053e480, 0xc00021e100, 0x0)
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1313 +0xd97
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000486050, 0xc00007f680, 0x1fd4800, 0xc00053e480, 0xc00021e100)
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:722 +0xbb
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-08-18T12:02:23.322-0500 [DEBUG] plugin.terraform-provider-databricks_v0.2.3: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:720 +0xa1
2020-08-18T12:02:23.324-0500 [DEBUG] plugin: plugin process exited: path=/Users/daniel/.terraform.d/plugins/terraform-provider-databricks_v0.2.3 pid=17505 error="exit status 2"
2020-08-18T12:02:23.324-0500 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020/08/18 12:02:23 [DEBUG] databricks_cluster.db_cluster: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/08/18 12:02:23 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2020/08/18 12:02:23 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020-08-18T12:02:24.671-0500 [DEBUG] plugin: plugin exited
````

**Comment by dgonzalezp** [comment]
```terraform
2020/08/18 11:57:19 [WARN] Provider "registry.terraform.io/-/databricks" produced an invalid plan for databricks_cluster.db_cluster, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .library_egg: planned value cty.SetValEmpty(cty.Object(map[string]cty.Type{"messages":cty.List(cty.String), "path":cty.String, "status":cty.String})) does not match config value cty.NullVal(cty.Set(cty.Object(map[string]cty.Type{"messages":cty.List(cty.String), "path":cty.String, "status":cty.String})))
      - .autoscale: planned value cty.SetVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"max_workers":cty.NumberIntVal(3), "min_workers":cty.NumberIntVal(1)})}) does not match config value cty.SetVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"max_workers":cty.NumberIntVal(3), "min_workers":cty.NumberIntVal(1)})})
      - .library_cran: planned value cty.SetValEmpty(cty.Object(map[string]cty.Type{"messages":cty.String, "package":cty.String, "repo":cty.String, "status":cty.String})) does not match config value cty.NullVal(cty.Set(cty.Object(map[string]cty.Type{"messages":cty.String, "package":cty.String, "repo":cty.String, "status":cty.String})))
      - .library_pypi: planned value cty.SetValEmpty(cty.Object(map[string]cty.Type{"messages":cty.List(cty.String), "package":cty.String, "repo":cty.String, "status":cty.String})) does not match config value cty.NullVal(cty.Set(cty.Object(map[string]cty.Type{"messages":cty.List(cty.String), "package":cty.String, "repo":cty.String, "status":cty.String})))
      - .library_whl: planned value cty.SetValEmpty(cty.Object(map[string]cty.Type{"messages":cty.List(cty.String), "path":cty.String, "status":cty.String})) does not match config value cty.NullVal(cty.Set(cty.Object(map[string]cty.Type{"messages":cty.List(cty.String), "path":cty.String, "status":cty.String})))
ring, "exclusions":cty.List(cty.String), "messages":cty.List(cty.String), "repo":cty.String, "status":cty.String})) does not match config value cty.NullVal(cty.Set(cty.Object(map[string]cty.Type{"coordinates":cty.String, "exclusions":cty.List(cty.String), "messages":cty.List(cty.String), "repo":cty.String, "status":cty.String})))
      - .library_jar: planned value cty.SetValEmpty(cty.Object(map[string]cty.Type{"messages":cty.List(cty.String), "path":cty.String, "status":cty.String})) does not match config value cty.NullVal(cty.Set(cty.Object(map[string]cty.Type{"messages":cty.List(cty.String), "path":cty.String, "status":cty.String})))
````

**Comment by dgonzalezp** [comment]
```terraform
2020/08/18 11:57:45 [WARN] Provider "registry.terraform.io/-/databricks" produced an invalid plan for databricks_cluster.db_cluster, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .autoscale: planned value cty.SetVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"max_workers":cty.NumberIntVal(3), "min_workers":cty.NumberIntVal(1)})}) does not match config value cty.SetVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"max_workers":cty.NumberIntVal(3), "min_workers":cty.NumberIntVal(1)})})
      - .library_cran: planned value cty.SetValEmpty(cty.Object(map[string]cty.Type{"messages":cty.String, "package":cty.String, "repo":cty.String, "status":cty.String})) does not match config value cty.NullVal(cty.Set(cty.Object(map[string]cty.Type{"messages":cty.String, "package":cty.String, "repo":cty.String, "status":cty.String})))
      - .library_maven: planned value cty.SetValEmpty(cty.Object(map[string]cty.Type{"coordinates":cty.String, "exclusions":cty.List(cty.String), "messages":cty.List(cty.String), "repo":cty.String, "status":cty.String})) does not match config value cty.NullVal(cty.Set(cty.Object(map[string]cty.Type{"coordinates":cty.String, "exclusions":cty.List(cty.String), "messages":cty.List(cty.String), "repo":cty.String, "status":cty.String})))
      - .library_pypi: planned value cty.SetValEmpty(cty.Object(map[string]cty.Type{"messages":cty.List(cty.String), "package":cty.String, "repo":cty.String, "status":cty.String})) does not match config value cty.NullVal(cty.Set(cty.Object(map[string]cty.Type{"messages":cty.List(cty.String), "package":cty.String, "repo":cty.String, "status":cty.String})))
us":cty.String})))
      - .library_jar: planned value cty.SetValEmpty(cty.Object(map[string]cty.Type{"messages":cty.List(cty.String), "path":cty.String, "status":cty.String})) does not match config value cty.NullVal(cty.Set(cty.Object(map[string]cty.Type{"messages":cty.List(cty.String), "path":cty.String, "status":cty.String})))
      - .library_egg: planned value cty.SetValEmpty(cty.Object(map[string]cty.Type{"messages":cty.List(cty.String), "path":cty.String, "status":cty.String})) does not match config value cty.NullVal(cty.Set(cty.Object(map[string]cty.Type{"messages":cty.List(cty.String), "path":cty.String, "status":cty.String})))
2020-08-18T11:57:45.150-0500 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
```
