### ISSUE TITLE
[ISSUE] Unable to create S3 mounts

### ISSUE THREAD

**Issue by thai-intelematics** [databrickslabs/terraform-provider-databricks#418]
### Terraform Version
Terraform: 0.13.5
Databricks provider: 0.2.8

### Affected Resource(s)
- `databricks_aws_s3_mount`

### Environment variable names
N/A

### Terraform Configuration Files
```hcl
resource "databricks_instance_profile" "databricks_compute" {
  instance_profile_arn = "<instance_profile_arn>"
  skip_validation      = false
}

locals {
  s3_mounts = {
    "dbfs_scratch" = "tf-${terraform.workspace}-dbfs-scratch"
  }
}

resource "databricks_aws_s3_mount" "s3_mount" {
  for_each = local.s3_mounts

  mount_name       = each.key
  s3_bucket_name   = each.value
  instance_profile = databricks_instance_profile.databricks_compute.id
}

```

### Debug Output
```
2020-11-25T16:54:58.095+1100 [INFO]  plugin.terraform-provider-databricks_v0.2.8: [INFO] Executing python command on 1123-234138-call876:
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: def safe_mount(mount_point, mount_source, configs):
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:     for mount in dbutils.fs.mounts():
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:         if mount.mountPoint == mount_point and mount.source == mount_source:
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:             return
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:     try:
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:         dbutils.fs.mount(mount_source, mount_point, extra_configs=configs)
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:         dbutils.fs.refreshMounts()
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:         dbutils.fs.ls(mount_point)
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:         return mount_source
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:     except Exception as e:
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:         try:
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:             dbutils.fs.unmount(mount_point)
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:         except Exception as e2:
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:             print("Failed to unmount", e2)
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:         raise e
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: mount_source = safe_mount("/mnt/dbfs_scratch", "s3a://intelematics-dac-tf-dev-ci-dbfs-scratch", {})
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: dbutils.notebook.exit(mount_source)
2020-11-25T16:54:58.095+1100 [INFO]  plugin.terraform-provider-databricks_v0.2.8: [INFO] POST /contexts/create {
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:   "clusterId": "1123-234138-call876",
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:   "language": "python"
2020-11-25T16:54:58.095+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: }
2020-11-25T16:54:58.248+1100 [INFO]  plugin.terraform-provider-databricks_v0.2.8: [INFO] 200 OK {
2020-11-25T16:54:58.248+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:   "id": "3845165776084034518"
2020-11-25T16:54:58.248+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: } <- POST /contexts/create
2020-11-25T16:54:58.248+1100 [INFO]  plugin.terraform-provider-databricks_v0.2.8: [INFO] GET /contexts/status?clusterId=1123-234138-call876&contextId=3845165776084034518
2020-11-25T16:54:58.394+1100 [INFO]  plugin.terraform-provider-databricks_v0.2.8: [INFO] 200 OK {
2020-11-25T16:54:58.394+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:   "id": "3845165776084034518",
2020-11-25T16:54:58.394+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:   "status": "Pending"
2020-11-25T16:54:58.394+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: } <- GET /contexts/status?clusterId=1123-234138-call876&contextId=3845165776084034518
2020-11-25T16:54:58.394+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: [DEBUG] Waiting for context to go to running, current state is Pending


databricks_aws_s3_mount.s3_mount["dbfs_scratch"]: Still creating... [1m10s elapsed]
2020-11-25T16:56:08.975+1100 [INFO]  plugin.terraform-provider-databricks_v0.2.8: [INFO] GET /commands/status?clusterId=1123-234138-call876&commandId=3a601163-d3c7-40f9-9c61-deb92c7a2c9d&contextId=3845165776084034518
2020-11-25T16:56:09.929+1100 [INFO]  plugin.terraform-provider-databricks_v0.2.8: [INFO] 200 OK {
2020-11-25T16:56:09.929+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:   "id": "3a601163-d3c7-40f9-9c61-deb92c7a2c9d",
2020-11-25T16:56:09.929+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:   "results": null,
2020-11-25T16:56:09.929+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:   "status": "Running"
2020-11-25T16:56:09.929+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: } <- GET /commands/status?clusterId=1123-234138-call876&commandId=3a601163-d3c7-40f9-9c61-deb92c7a2c9d&contextId=3845165776084034518
2020-11-25T16:56:09.929+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: [DEBUG] Waiting for command to finish, current state is: Running.
2020/11/25 16:56:11 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
2020/11/25 16:56:11 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/databrickslabs/databricks\"] (close)" is waiting for "databricks_aws_s3_mount.s3_mount[\"dbfs_scratch\"]"
2020/11/25 16:56:11 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "databricks_aws_s3_mount.s3_mount[\"dbfs_scratch\"]"
2020-11-25T16:56:14.932+1100 [INFO]  plugin.terraform-provider-databricks_v0.2.8: [INFO] GET /commands/status?clusterId=1123-234138-call876&commandId=3a601163-d3c7-40f9-9c61-deb92c7a2c9d&contextId=3845165776084034518
2020-11-25T16:56:15.042+1100 [INFO]  plugin.terraform-provider-databricks_v0.2.8: [INFO] 200 OK {
2020-11-25T16:56:15.042+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:   "id": "3a601163-d3c7-40f9-9c61-deb92c7a2c9d",
2020-11-25T16:56:15.042+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:   "results": {
2020-11-25T16:56:15.042+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:     "cause": "---------------------------------------------------------------------------\nExecutionError      ... (4503 more bytes)",
2020-11-25T16:56:15.042+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:     "resultType": "error",
2020-11-25T16:56:15.042+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:     "summary": "java.io.FileNotFoundException: No such file or directory: /"
2020-11-25T16:56:15.042+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:   },
2020-11-25T16:56:15.042+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:   "status": "Finished"
2020-11-25T16:56:15.042+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: } <- GET /commands/status?clusterId=1123-234138-call876&commandId=3a601163-d3c7-40f9-9c61-deb92c7a2c9d&contextId=3845165776084034518
2020-11-25T16:56:15.042+1100 [INFO]  plugin.terraform-provider-databricks_v0.2.8: [INFO] GET /commands/status?clusterId=1123-234138-call876&commandId=3a601163-d3c7-40f9-9c61-deb92c7a2c9d&contextId=3845165776084034518
2020-11-25T16:56:15.115+1100 [INFO]  plugin.terraform-provider-databricks_v0.2.8: [INFO] 200 OK {
2020-11-25T16:56:15.115+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:   "id": "3a601163-d3c7-40f9-9c61-deb92c7a2c9d",
2020-11-25T16:56:15.115+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:   "results": {
2020-11-25T16:56:15.115+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:     "cause": "---------------------------------------------------------------------------\nExecutionError      ... (4503 more bytes)",
2020-11-25T16:56:15.115+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:     "resultType": "error",
2020-11-25T16:56:15.115+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:     "summary": "java.io.FileNotFoundException: No such file or directory: /"
2020-11-25T16:56:15.116+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:   },
2020-11-25T16:56:15.116+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:   "status": "Finished"
2020-11-25T16:56:15.116+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: } <- GET /commands/status?clusterId=1123-234138-call876&commandId=3a601163-d3c7-40f9-9c61-deb92c7a2c9d&contextId=3845165776084034518
2020-11-25T16:56:15.116+1100 [INFO]  plugin.terraform-provider-databricks_v0.2.8: [INFO] POST /contexts/destroy {
2020-11-25T16:56:15.116+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:   "clusterId": "1123-234138-call876",
2020-11-25T16:56:15.116+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:   "contextId": "3845165776084034518"
2020-11-25T16:56:15.116+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: }
2020-11-25T16:56:15.168+1100 [INFO]  plugin.terraform-provider-databricks_v0.2.8: [INFO] 200 OK {
2020-11-25T16:56:15.168+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:   "id": "3845165776084034518"
2020-11-25T16:56:15.168+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: } <- POST /contexts/destroy
2020-11-25T16:56:15.168+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: [DEBUG] error caused by command: ---------------------------------------------------------------------------
2020-11-25T16:56:15.168+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: ExecutionError                            Traceback (most recent call last)
2020-11-25T16:56:15.168+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: <command--1> in <module>
2020-11-25T16:56:15.168+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:      14             print("Failed to unmount", e2)
2020-11-25T16:56:15.168+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:      15         raise e
2020-11-25T16:56:15.168+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: ---> 16 mount_source = safe_mount("/mnt/dbfs_scratch", "s3a://intelematics-dac-tf-dev-ci-dbfs-scratch", {})
2020-11-25T16:56:15.168+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:      17 dbutils.notebook.exit(mount_source)
2020-11-25T16:56:15.168+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:
2020-11-25T16:56:15.168+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: <command--1> in safe_mount(mount_point, mount_source, configs)
2020-11-25T16:56:15.168+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:      13         except Exception as e2:
2020-11-25T16:56:15.168+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:      14             print("Failed to unmount", e2)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: ---> 15         raise e
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:      16 mount_source = safe_mount("/mnt/dbfs_scratch", "s3a://intelematics-dac-tf-dev-ci-dbfs-scratch", {})
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:      17 dbutils.notebook.exit(mount_source)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: <command--1> in safe_mount(mount_point, mount_source, configs)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:       6         dbutils.fs.mount(mount_source, mount_point, extra_configs=configs)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:       7         dbutils.fs.refreshMounts()
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: ----> 8         dbutils.fs.ls(mount_point)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:       9         return mount_source
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:      10     except Exception as e:
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: /local_disk0/tmp/1606283126847-0/dbutils.py in f_with_exception_handling(*args, **kwargs)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:     312                     exc.__context__ = None
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:     313                     exc.__cause__ = None
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: --> 314                     raise exc
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:     315             return f_with_exception_handling
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:     316
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8:
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: ExecutionError: An error occurred while calling z:com.databricks.backend.daemon.dbutils.FSUtils.ls.
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: : java.io.FileNotFoundException: No such file or directory: /
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.s3a.S3AFileSystem.getFileStatus(S3AFileSystem.java:1665)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.s3a.S3AFileSystem.listStatus(S3AFileSystem.java:1316)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.s3a.S3AFileSystem.listStatus(S3AFileSystem.java:1293)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.backend.daemon.data.client.DBFSV2$$anonfun$listStatus$1$$anonfun$apply$2.apply(DatabricksFileSystemV2.scala:95)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.backend.daemon.data.client.DBFSV2$$anonfun$listStatus$1$$anonfun$apply$2.apply(DatabricksFileSystemV2.scala:92)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.s3a.S3AExeceptionUtils$.convertAWSExceptionToJavaIOException(DatabricksStreamUtils.scala:108)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.backend.daemon.data.client.DBFSV2$$anonfun$listStatus$1.apply(DatabricksFileSystemV2.scala:92)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.backend.daemon.data.client.DBFSV2$$anonfun$listStatus$1.apply(DatabricksFileSystemV2.scala:92)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.logging.UsageLogging$$anonfun$recordOperation$1.apply(UsageLogging.scala:430)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:238)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:233)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withAttributionContext(DatabricksFileSystemV2.scala:453)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:275)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withAttributionTags(DatabricksFileSystemV2.scala:453)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.logging.UsageLogging$class.recordOperation(UsageLogging.scala:411)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.recordOperation(DatabricksFileSystemV2.scala:453)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.backend.daemon.data.client.DBFSV2.listStatus(DatabricksFileSystemV2.scala:91)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.backend.daemon.data.client.DatabricksFileSystem.listStatus(DatabricksFileSystem.scala:150)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.backend.daemon.dbutils.FSUtils$$anonfun$ls$1.apply(DBUtilsCore.scala:86)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.backend.daemon.dbutils.FSUtils$$anonfun$ls$1.apply(DBUtilsCore.scala:85)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.backend.daemon.dbutils.FSUtils$.com$databricks$backend$daemon$dbutils$FSUtils$$withFsSafetyCheck(DBUtilsCore.scala:81)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.backend.daemon.dbutils.FSUtils$.ls(DBUtilsCore.scala:85)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at com.databricks.backend.daemon.dbutils.FSUtils.ls(DBUtilsCore.scala)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at py4j.Gateway.invoke(Gateway.java:295)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at py4j.GatewayConnection.run(GatewayConnection.java:251)
2020-11-25T16:56:15.169+1100 [DEBUG] plugin.terraform-provider-databricks_v0.2.8: 	at java.lang.Thread.run(Thread.java:748)
```

### Expected Behavior
The mount should be applied succesfully.

### Actual Behavior
Some misleading error was returned.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

NOTE: If I was able to mount the bucket by manually running the Python commands in a note book

**Comment by nfx** [comment]
@thai-intelematics this is not the issue of provider, but rather IAM profile not being able to access the bucket. Which may not exist as well.

`dbutils.fs.ls(mount_point)` inside verifies if data on the mount point is accessible and throws error if it doesn't. And it unmounts a bucket, because it's found to be inaccessible. the root cause may be in some wrong configuration of S3 bucket.
