### ISSUE TITLE
[ISSUE] azure_adls_gen2_mount crash

### ISSUE THREAD

**Issue by stanbiryukov** [databrickslabs/terraform-provider-databricks#448]
Hi there,

I get this crash log below after attempting to mount a data lake storage account using `azure_adls_gen2_mount`. Databricks provider version is `0.2.9`. Terraform version is `13.5`.
 
Service principal has storage blob contributor RBAC on the storage account.

```
Error: rpc error: code = Unavailable desc = transport is closing


panic: Invalid diagnostic: empty summary. This is always a bug in the provider implementation
2020-12-19T01:17:06.773Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: 
2020-12-19T01:17:06.773Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: goroutine 27 [running]:
2020-12-19T01:17:06.773Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: github.com/hashicorp/terraform-plugin-sdk/v2/internal/plugin/convert.DiagsToProto(0xc000597100, 0x1, 0x1, 0xc0002d57e8, 0x8d02b8, 0xc0002d57b8)
2020-12-19T01:17:06.773Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.2-0.20200828083434-d39628234432/internal/plugin/convert/diagnostics.go:71 +0x38a
2020-12-19T01:17:06.773Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: github.com/hashicorp/terraform-plugin-sdk/v2/internal/plugin/convert.AppendProtoDiag(0x0, 0x0, 0x0, 0x1045cc0, 0xc00061fce0, 0x11a9200, 0xc00020c000, 0xc00038e000)
2020-12-19T01:17:06.773Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.2-0.20200828083434-d39628234432/internal/plugin/convert/diagnostics.go:24 +0x7e3
2020-12-19T01:17:06.773Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: github.com/hashicorp/terraform-plugin-sdk/v2/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0001a3640, 0x14d5aa0, 0xc0001ad280, 0xc0004a2e00, 0xc0001a3640, 0xc0001ad280, 0x0)
2020-12-19T01:17:06.773Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.2-0.20200828083434-d39628234432/internal/helper/plugin/grpc_provider.go:953 +0x924
2020-12-19T01:17:06.773Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ApplyResourceChange_Handler.func1(0x14d5aa0, 0xc0001ad280, 0x11768c0, 0xc0004a2e00, 0xc0001ad280, 0x108da80, 0xc0001c0a01, 0xc000602140)
2020-12-19T01:17:06.773Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.2-0.20200828083434-d39628234432/internal/tfplugin5/tfplugin5.pb.go:3312 +0x86
2020-12-19T01:17:06.773Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve.func3.1(0x14d5b60, 0xc0002b2090, 0x11768c0, 0xc0004a2e00, 0xc000602120, 0xc000602140, 0xc0003d6b58, 0x5a32f8, 0x1120800, 0xc0002b2090)
2020-12-19T01:17:06.773Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.2-0.20200828083434-d39628234432/plugin/serve.go:76 +0x87
2020-12-19T01:17:06.773Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x118c920, 0xc0001a3640, 0x14d5b60, 0xc0002b2090, 0xc0001c0a80, 0xc00000d680, 0x14d5b60, 0xc0002b2090, 0xc000264b00, 0x2a4)
2020-12-19T01:17:06.773Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: 	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.2-0.20200828083434-d39628234432/internal/tfplugin5/tfplugin5.pb.go:3314 +0x14b
2020-12-19T01:17:06.773Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022c000, 0x14e4ea0, 0xc00008be00, 0xc000238200, 0xc00058b980, 0x1cb4ce0, 0x0, 0x0, 0x0)
2020-12-19T01:17:06.773Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1171 +0x4fd
2020-12-19T01:17:06.773Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: google.golang.org/grpc.(*Server).handleStream(0xc00022c000, 0x14e4ea0, 0xc00008be00, 0xc000238200, 0x0)
2020-12-19T01:17:06.773Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1494 +0xd27
2020-12-19T01:17:06.774Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0005922c0, 0xc00022c000, 0x14e4ea0, 0xc00008be00, 0xc000238200)
2020-12-19T01:17:06.774Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:834 +0xbb
2020-12-19T01:17:06.774Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-12-19T01:17:06.774Z [DEBUG] plugin.terraform-provider-databricks_v0.2.9: 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:832 +0x204
2020-12-19T01:17:06.775Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/databrickslabs/databricks/0.2.9/linux_amd64/terraform-provider-databricks_v0.2.9 pid=1062 error="exit status 2"
2020/12/19 01:17:06 [DEBUG] databricks_azure_adls_gen2_mount.mnt: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/12/19 01:17:06 [TRACE] eval: *terraform.EvalMaybeTainted
2020/12/19 01:17:06 [TRACE] EvalMaybeTainted: databricks_azure_adls_gen2_mount.mnt encountered an error during creation, so it is now marked as tainted
2020/12/19 01:17:06 [TRACE] eval: *terraform.EvalWriteState
2020/12/19 01:17:06 [TRACE] EvalWriteState: removing state object for databricks_azure_adls_gen2_mount.mnt
2020/12/19 01:17:06 [TRACE] eval: *terraform.EvalApplyProvisioners
2020/12/19 01:17:06 [TRACE] EvalApplyProvisioners: databricks_azure_adls_gen2_mount.mnt has no state, so skipping provisioners
2020/12/19 01:17:06 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/databrickslabs/databricks\"] (close)" errored, so skipping
2020/12/19 01:17:06 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020-12-19T01:17:06.848Z [DEBUG] plugin: plugin exited
```

**Comment by nfx** [comment]
@stanbiryukov too little information about the crash. please reproduce it and provide more debug logs.

**Comment by stanbiryukov** [comment]
@nfx I reran this using the `databricks_azure_blob_mount ` approach and got a more informative error around permissions. I went back and included the `Microsoft.Storage` endpoint in the databricks 'public' subnet (not just the private), and granted that subnet network access to the storage account. The mount worked thereafter when both subnets were allowed traffic to the storage account.

**Comment by nfx** [comment]
Some of those errors might have been way more descriptive, I know. Root cause is usually hidden in stack traces. Feel free to open pull requests/issues with suggestions on concrete error to resolution, we can easily add regex matching for those
