### ISSUE TITLE
[ISSUE] 0.3.8 plugin crashed

### ISSUE THREAD

**Issue by aravishdatabricks** [databrickslabs/terraform-provider-databricks#854]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

0.3.8 plugin crashed
╰─❯ tf plan
╷
│ Error: Plugin did not respond
│
│   with data.databricks_node_type.smallest,
│   on instance_pools.tf line 15, in data "databricks_node_type" "smallest":
│   15: data "databricks_node_type" "smallest" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with data.databricks_spark_version.latest_lts,
│   on instance_pools.tf line 18, in data "databricks_spark_version" "latest_lts":
│   18: data "databricks_spark_version" "latest_lts" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with data.databricks_node_type.nodes,
│   on instance_pools.tf line 22, in data "databricks_node_type" "nodes":
│   22: data "databricks_node_type" "nodes" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-databricks_v0.3.8 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x17273d1]

goroutine 43 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0000b0918, 0x1f67de8, 0xc0005d7540, 0xc00020e580, 0xc0005d7540, 0x100b665, 0x1cb5700)
	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:1126 +0x491
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc000133a00, 0x1f67e90, 0xc0005d7540, 0xc000338460, 0xc000133a00, 0xc000333410, 0xc0005e7ba0)
	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:247 +0xe5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler(0x1cfa9c0, 0xc000133a00, 0x1f67e90, 0xc000333410, 0xc000340240, 0x0, 0x1f67e90, 0xc000333410, 0xc000358000, 0xc9)
	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000fca80, 0x1f71f38, 0xc000001c80, 0xc0008ba120, 0xc000552cf0, 0x258b1b0, 0x0, 0x0, 0x0)
	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:1297 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0000fca80, 0x1f71f38, 0xc000001c80, 0xc0008ba120, 0x0)
	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:1626 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000218270, 0xc0000fca80, 0x1f71f38, 0xc000001c80, 0xc0008ba120)
	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:941 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:939 +0x1fd

Error: The terraform-provider-databricks_v0.3.8 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Configuration
```hcl
terraform {
  required_providers {
    databricks = {
      source  = "databrickslabs/databricks"
      version = "0.3.8"
    }
  }
}

provider "databricks" {
  host  = "https://cust-success.cloud.databricks.com/"
  token = "dapixxxxxxxxxx"
}

data "databricks_node_type" "smallest" {
}

data "databricks_spark_version" "latest_lts" {
  long_term_support = true
}

data "databricks_node_type" "nodes" {
  category      = "General Purpose"
  min_cores     = 4
  min_memory_gb = 16
}

resource "databricks_instance_pool" "tf_node_pool" {
  instance_pool_name = "Terraform node pool"
  min_idle_instances = 0
  max_capacity       = 3
  node_type_id       = data.databricks_node_type.nodes.id
  // data.databricks_node_type.nodes.id
  // data.databricks_node_type.smallest.id
  preloaded_spark_versions = [var.databricks_spark_version]
  aws_attributes {
    spot_bid_price_percent = 100
    availability           = "SPOT"
    zone_id                = "us-west-2b"
  }
  idle_instance_autotermination_minutes = 10
  enable_elastic_disk                   = true
  disk_spec {
    disk_type {
      ebs_volume_type = "GENERAL_PURPOSE_SSD"
    }
    disk_size  = 50
    disk_count = 1
  }
  custom_tags = { "From terraform" : true }
}

resource "databricks_cluster" "tf_cluster" {
  cluster_name  = "Terraform Cluster"
  spark_version = var.databricks_spark_version
  // data.databricks_spark_version.latest_lts.id
  instance_pool_id = databricks_instance_pool.tf_node_pool.id
  // instance_pool_id
  autotermination_minutes = 20
  is_pinned               = true
  autoscale {
    min_workers = 1
    max_workers = 2
  }
}

variable "databricks_spark_version" {
  default     = "9.0.x-scala2.12"
  description = "Spark version to be used inside Databricks"
  type        = string
}
```

### Expected Behavior
What should have happened?
Should not crash

### Actual Behavior
What actually happened?
Error: The terraform-provider-databricks_v0.3.8 plugin crashed!

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Terraform and provider versions

╰─❯ tf -version
Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.3.8

Your version of Terraform is out of date! The latest version

### Debug Output
╰─❯ TF_LOG=DEBUG terraform plan 2>&1 | grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'
2021-10-09T15:55:51.328Z [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/databrickslabs/databricks/0.3.8/darwin_amd64/terraform-provider-databricks_v0.3.8 args=[.terraform/providers/registry.terraform.io/databrickslabs/databricks/0.3.8/darwin_amd64/terraform-provider-databricks_v0.3.8]
path=.terraform/providers/registry.terraform.io/databrickslabs/databricks/0.3.8/darwin_amd64/terraform-provider-databricks_v0.3.8 pid=81822
2021-10-09T15:55:51.331Z [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/databrickslabs/databricks/0.3.8/darwin_amd64/terraform-provider-databricks_v0.3.8
2021-10-09T15:55:51.347Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: Databricks Terraform Provider (experimental)
2021-10-09T15:55:51.347Z [DEBUG] provider.terraform-provider-databricks_v0.3.8:
2021-10-09T15:55:51.347Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: Version 0.3.8
2021-10-09T15:55:51.347Z [DEBUG] provider.terraform-provider-databricks_v0.3.8:
2021-10-09T15:55:51.347Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs
2021-10-09T15:55:51.347Z [DEBUG] provider.terraform-provider-databricks_v0.3.8:
2021-10-09T15:55:51.351Z [INFO]  provider.terraform-provider-databricks_v0.3.8: configuring server automatic mTLS: timestamp=2021-10-09T15:55:51.351Z
address=/var/folders/7f/n1kcjs9n2f32vxqd5kbfjll00000gp/T/plugin192884525 network=unix timestamp=2021-10-09T15:55:51.383Z
path=.terraform/providers/registry.terraform.io/databrickslabs/databricks/0.3.8/darwin_amd64/terraform-provider-databricks_v0.3.8 pid=81822
2021-10-09T15:55:51.431Z [DEBUG] ProviderTransformer: "databricks_cluster.tf_cluster" (*terraform.NodeValidatableResource) needs provider["registry.terraform.io/databrickslabs/databricks"]
2021-10-09T15:55:51.431Z [DEBUG] ProviderTransformer: "data.databricks_node_type.smallest" (*terraform.NodeValidatableResource) needs provider["registry.terraform.io/databrickslabs/databricks"]
2021-10-09T15:55:51.431Z [DEBUG] ProviderTransformer: "data.databricks_spark_version.latest_lts" (*terraform.NodeValidatableResource) needs provider["registry.terraform.io/databrickslabs/databricks"]
2021-10-09T15:55:51.431Z [DEBUG] ProviderTransformer: "data.databricks_node_type.nodes" (*terraform.NodeValidatableResource) needs provider["registry.terraform.io/databrickslabs/databricks"]
2021-10-09T15:55:51.431Z [DEBUG] ProviderTransformer: "databricks_instance_pool.tf_node_pool" (*terraform.NodeValidatableResource) needs provider["registry.terraform.io/databrickslabs/databricks"]
2021-10-09T15:55:51.431Z [DEBUG] ReferenceTransformer: "databricks_instance_pool.tf_node_pool" references: [data.databricks_node_type.nodes var.databricks_spark_version]
2021-10-09T15:55:51.431Z [DEBUG] ReferenceTransformer: "databricks_cluster.tf_cluster" references: [var.databricks_spark_version databricks_instance_pool.tf_node_pool]
2021-10-09T15:55:51.431Z [DEBUG] ReferenceTransformer: "data.databricks_node_type.smallest" references: []
2021-10-09T15:55:51.431Z [DEBUG] ReferenceTransformer: "data.databricks_spark_version.latest_lts" references: []
2021-10-09T15:55:51.431Z [DEBUG] ReferenceTransformer: "data.databricks_node_type.nodes" references: []
2021-10-09T15:55:51.431Z [DEBUG] ReferenceTransformer: "var.databricks_spark_version" references: []
2021-10-09T15:55:51.432Z [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/databrickslabs/databricks\"]" references: []
2021-10-09T15:55:51.464Z [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/databrickslabs/databricks/0.3.8/darwin_amd64/terraform-provider-databricks_v0.3.8 args=[.terraform/providers/registry.terraform.io/databrickslabs/databricks/0.3.8/darwin_amd64/terraform-provider-databricks_v0.3.8]
path=.terraform/providers/registry.terraform.io/databrickslabs/databricks/0.3.8/darwin_amd64/terraform-provider-databricks_v0.3.8 pid=81823
2021-10-09T15:55:51.467Z [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/databrickslabs/databricks/0.3.8/darwin_amd64/terraform-provider-databricks_v0.3.8
2021-10-09T15:55:51.484Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: Databricks Terraform Provider (experimental)
2021-10-09T15:55:51.484Z [DEBUG] provider.terraform-provider-databricks_v0.3.8:
2021-10-09T15:55:51.484Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: Version 0.3.8
2021-10-09T15:55:51.484Z [DEBUG] provider.terraform-provider-databricks_v0.3.8:
2021-10-09T15:55:51.484Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs
2021-10-09T15:55:51.484Z [DEBUG] provider.terraform-provider-databricks_v0.3.8:
2021-10-09T15:55:51.486Z [INFO]  provider.terraform-provider-databricks_v0.3.8: configuring server automatic mTLS: timestamp=2021-10-09T15:55:51.486Z
address=/var/folders/7f/n1kcjs9n2f32vxqd5kbfjll00000gp/T/plugin212114458 network=unix timestamp=2021-10-09T15:55:51.520Z
path=.terraform/providers/registry.terraform.io/databrickslabs/databricks/0.3.8/darwin_amd64/terraform-provider-databricks_v0.3.8 pid=81823
2021-10-09T15:55:51.574Z [DEBUG] ProviderTransformer: "data.databricks_node_type.smallest (expand)" (*terraform.nodeExpandPlannableResource) needs provider["registry.terraform.io/databrickslabs/databricks"]
2021-10-09T15:55:51.574Z [DEBUG] ProviderTransformer: "databricks_instance_pool.tf_node_pool (expand)" (*terraform.nodeExpandPlannableResource) needs provider["registry.terraform.io/databrickslabs/databricks"]
2021-10-09T15:55:51.574Z [DEBUG] ProviderTransformer: "databricks_cluster.tf_cluster (expand)" (*terraform.nodeExpandPlannableResource) needs provider["registry.terraform.io/databrickslabs/databricks"]
2021-10-09T15:55:51.574Z [DEBUG] ProviderTransformer: "data.databricks_spark_version.latest_lts (expand)" (*terraform.nodeExpandPlannableResource) needs provider["registry.terraform.io/databrickslabs/databricks"]
2021-10-09T15:55:51.574Z [DEBUG] ProviderTransformer: "data.databricks_node_type.nodes (expand)" (*terraform.nodeExpandPlannableResource) needs provider["registry.terraform.io/databrickslabs/databricks"]
2021-10-09T15:55:51.574Z [DEBUG] ReferenceTransformer: "data.databricks_node_type.smallest (expand)" references: []
2021-10-09T15:55:51.574Z [DEBUG] ReferenceTransformer: "var.databricks_spark_version" references: []
2021-10-09T15:55:51.574Z [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/databrickslabs/databricks\"]" references: []
2021-10-09T15:55:51.574Z [DEBUG] ReferenceTransformer: "databricks_instance_pool.tf_node_pool (expand)" references: [data.databricks_node_type.nodes (expand) var.databricks_spark_version]
2021-10-09T15:55:51.574Z [DEBUG] ReferenceTransformer: "databricks_cluster.tf_cluster (expand)" references: [databricks_instance_pool.tf_node_pool (expand) var.databricks_spark_version]
2021-10-09T15:55:51.574Z [DEBUG] ReferenceTransformer: "data.databricks_spark_version.latest_lts (expand)" references: []
2021-10-09T15:55:51.574Z [DEBUG] ReferenceTransformer: "data.databricks_node_type.nodes (expand)" references: []
2021-10-09T15:55:51.606Z [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/databrickslabs/databricks/0.3.8/darwin_amd64/terraform-provider-databricks_v0.3.8 args=[.terraform/providers/registry.terraform.io/databrickslabs/databricks/0.3.8/darwin_amd64/terraform-provider-databricks_v0.3.8]
path=.terraform/providers/registry.terraform.io/databrickslabs/databricks/0.3.8/darwin_amd64/terraform-provider-databricks_v0.3.8 pid=81824
2021-10-09T15:55:51.610Z [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/databrickslabs/databricks/0.3.8/darwin_amd64/terraform-provider-databricks_v0.3.8
2021-10-09T15:55:51.627Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: Databricks Terraform Provider (experimental)
2021-10-09T15:55:51.627Z [DEBUG] provider.terraform-provider-databricks_v0.3.8:
2021-10-09T15:55:51.627Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: Version 0.3.8
2021-10-09T15:55:51.627Z [DEBUG] provider.terraform-provider-databricks_v0.3.8:
2021-10-09T15:55:51.627Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs
2021-10-09T15:55:51.627Z [DEBUG] provider.terraform-provider-databricks_v0.3.8:
2021-10-09T15:55:51.629Z [INFO]  provider.terraform-provider-databricks_v0.3.8: configuring server automatic mTLS: timestamp=2021-10-09T15:55:51.629Z
address=/var/folders/7f/n1kcjs9n2f32vxqd5kbfjll00000gp/T/plugin862741759 network=unix timestamp=2021-10-09T15:55:51.669Z
2021-10-09T15:55:51.722Z [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/databrickslabs/databricks\"]" changed the config value, but that value is unused
2021-10-09T15:55:51.722Z [INFO]  provider.terraform-provider-databricks_v0.3.8: Explicit and implicit attributes: host, token: timestamp=2021-10-09T15:55:51.722Z
2021-10-09T15:55:51.723Z [DEBUG] Resource instance state not found for node "data.databricks_node_type.smallest", instance data.databricks_node_type.smallest
2021-10-09T15:55:51.723Z [DEBUG] ReferenceTransformer: "data.databricks_node_type.smallest" references: []
2021-10-09T15:55:51.723Z [DEBUG] Resource instance state not found for node "data.databricks_node_type.nodes", instance data.databricks_node_type.nodes
2021-10-09T15:55:51.723Z [DEBUG] ReferenceTransformer: "data.databricks_node_type.nodes" references: []
2021-10-09T15:55:51.723Z [DEBUG] Resource instance state not found for node "data.databricks_spark_version.latest_lts", instance data.databricks_spark_version.latest_lts
2021-10-09T15:55:51.723Z [DEBUG] ReferenceTransformer: "data.databricks_spark_version.latest_lts" references: []
2021-10-09T15:55:51.724Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: Instance Diff is nil in Diff(): timestamp=2021-10-09T15:55:51.724Z
2021-10-09T15:55:51.728Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: PANIC: runtime error: invalid memory address or nil pointer dereference
2021-10-09T15:55:51.728Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x17273d1]
2021-10-09T15:55:51.728Z [DEBUG] provider.terraform-provider-databricks_v0.3.8:
2021-10-09T15:55:51.728Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: goroutine 14 [running]:
2021-10-09T15:55:51.728Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc000788900, 0x1f67de8, 0xc00085a0c0, 0xc0007f4080, 0xc00085a0c0, 0x100b665, 0x1cb5700)
2021-10-09T15:55:51.728Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: 	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:1126 +0x491
2021-10-09T15:55:51.728Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0000fb5a0, 0x1f67e90, 0xc00085a0c0, 0xc00070e000, 0xc0000fb5a0, 0xc00067c030, 0xc000648ba0)
2021-10-09T15:55:51.728Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: 	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:247 +0xe5
2021-10-09T15:55:51.728Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler(0x1cfa9c0, 0xc0000fb5a0, 0x1f67e90, 0xc00067c030, 0xc00070c000, 0x0, 0x1f67e90, 0xc00067c030, 0xc00067e0d0, 0xc9)
2021-10-09T15:55:51.728Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: 	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x214
2021-10-09T15:55:51.728Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000423a40, 0x1f71f38, 0xc000093080, 0xc0007ba6c0, 0xc00009e660, 0x258b1b0, 0x0, 0x0, 0x0)
2021-10-09T15:55:51.728Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: 	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:1297 +0x52b
2021-10-09T15:55:51.728Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: google.golang.org/grpc.(*Server).handleStream(0xc000423a40, 0x1f71f38, 0xc000093080, 0xc0007ba6c0, 0x0)
2021-10-09T15:55:51.728Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: 	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:1626 +0xd0c
2021-10-09T15:55:51.728Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000352170, 0xc000423a40, 0x1f71f38, 0xc000093080, 0xc0007ba6c0)
2021-10-09T15:55:51.728Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: 	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:941 +0xab
2021-10-09T15:55:51.728Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-10-09T15:55:51.728Z [DEBUG] provider.terraform-provider-databricks_v0.3.8: 	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:939 +0x1fd
path=.terraform/providers/registry.terraform.io/databrickslabs/databricks/0.3.8/darwin_amd64/terraform-provider-databricks_v0.3.8 pid=81824 error="exit status 2"
│   with data.databricks_node_type.smallest,
│   on instance_pools.tf line 15, in data "databricks_node_type" "smallest":
│   15: data "databricks_node_type" "smallest" {
│   with data.databricks_spark_version.latest_lts,
│   on instance_pools.tf line 18, in data "databricks_spark_version" "latest_lts":
│   18: data "databricks_spark_version" "latest_lts" {
│   with data.databricks_node_type.nodes,
│   on instance_pools.tf line 22, in data "databricks_node_type" "nodes":
│   22: data "databricks_node_type" "nodes" {
Stack trace from the terraform-provider-databricks_v0.3.8 plugin:
	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:1126 +0x491
	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:247 +0xe5
	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x214
	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:1297 +0x52b
	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:1626 +0xd0c
	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:941 +0xab
	/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:939 +0x1fd
Error: The terraform-provider-databricks_v0.3.8 plugin crashed!

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Important Factoids
Are there anything atypical about your accounts that we should know? 
None

**Comment by nfx** [comment]
@aravishdatabricks Please mail me the full stack trace, because I cannot see our code reference anywhere in traces. Is this one of or can you reproduce it?

I'll look into this on Monday

**Comment by aravishdatabricks** [comment]
Thank you @nfx for looking into this. I have emailed the logs.
